services:
  openbn:
    build:
      context: .
      args:
        INSTALL_GUROBI: "false"  # skip gurobi installation
    image: openbn-image
    container_name: openbn-container
    ports:
      - "8888:8888" # expose jupyter notebook port host:container
      - "8000:8000" # expose local server for Doxygen docs
    shm_size: "4g" # shared memory size
    deploy:
      resources:
        limits:
          memory: "8g"   # memory limit
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: ["gpu"]
              options:
                "device": "0"
    volumes:
      - .:/workspace # mount current directory to /workspace
    command: > 
      bash -c "
        doxygen Doxyfile && python3 -m http.server 8000 --directory /workspace/docs/html
      & jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token=''
      "