name: Generate and Deploy Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  generate_and_deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_NAME and IMAGE_TAG
        run: |
          echo "IMAGE_NAME=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          echo "CACHE_KEY_IMAGE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Restore cached Docker image
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: /tmp/image.tar
          key: ${{ runner.os }}-docker-${{ env.CACHE_KEY_IMAGE }}-${{ env.IMAGE_TAG }}

      - name: Load image from cache
        if: steps.cache-restore.outputs.cache-hit == 'true'
        run: docker load -i /tmp/image.tar

      - name: Log in to GitHub Docker Registry
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Pull & save image (cache miss)
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          docker pull "$IMAGE_NAME:$IMAGE_TAG"
          docker save "$IMAGE_NAME:$IMAGE_TAG" -o /tmp/image.tar

      - name: Save image to cache
        if: steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: /tmp/image.tar
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set execute permissions for bash scripts
        run: chmod +x ./scripts/gen_docs.sh

      - name: Generate Documentation
        run: docker run --rm -v "$(pwd):/workspace" "$IMAGE_NAME:$IMAGE_TAG" ./scripts/gen_docs.sh

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          path: sphinx/build/html
