name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_and_deploy_docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update && apt install -y \
            doxygen \
            graphviz \
            python3.10 \
            python3.10-dev \
            python3-pip \
          sudo apt clean && sudo rm -rf /var/lib/apt/lists/*
            
      - name: Install Python Packages
        run: |
          pip3 install --upgrade pip
          pip3 install \
            sphinx==8.1.3 \
            breathe==4.35.0

      - name: Generate Documentation
        run: chmod +x gen_docs.sh && ./gen_docs.sh

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          path: sphinx/build/html
