name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python and Install Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: |
          sudo apt update
          sudo apt install -y doxygen graphviz
          pip install sphinx==8.1.3 breathe==4.35.0

      - name: Build Documentation
        run: ./gen_docs.sh

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          path: sphinx/build/html
