name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_and_deploy_docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update && apt install -y \
            doxygen \
            graphviz \
            python3.10 \
            python3.10-dev \
            python3-pip \
            && rm -rf /var/lib/apt/lists/*

      -name: Set Python 3.10 as Default
      run: |
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
        sudo update-alternatives --set python3 /usr/bin/python3.10

      - name: Install Python Packages
        run: |
          pip3 install --upgrade pip
          pip3 install \
            sphinx==8.1.3 \
            breathe==4.35.0

      - name: Generate Documentation
        run: docker run --rm -v $PWD:/workspace openbnsl-image bash -c "chmod +x gen_docs.sh && ./gen_docs.sh"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          path: sphinx/build/html
