name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_and_deploy_docs:
    if : github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t openbnsl-image .

      - name: Generate Documentation
        run: docker run --rm -v $PWD:/workspace openbnsl-image bash -c "chmod +x gen_docs.sh && ./gen_docs.sh"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          path: sphinx/build/html
