name: Build, Test, and Format Check

on:
  pull_request:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  IMAGE_TAG: latest

jobs:
  build_test_and_format:
    name: Build, Test, and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Pull Docker Image
        run: docker pull $IMAGE_NAME:$IMAGE_TAG

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set execute permissions for bash scripts
        run: chmod +x ./scripts/build_test.sh ./scripts/run_test.sh ./scripts/format.sh

      - name: Run Build
        run: |
          docker run --rm -v "$(pwd):/workspace" $IMAGE_NAME:$IMAGE_TAG ./scripts/build_test.sh

      - name: Run Tests
        run: |
          docker run --rm -v "$(pwd):/workspace" $IMAGE_NAME:$IMAGE_TAG ./scripts/run_test.sh

      - name: Run Format Check
        run: |
          docker run --rm -v "$(pwd):/workspace" $IMAGE_NAME:$IMAGE_TAG ./scripts/format.sh --check