name: Build and Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y \
            build-essential \
            cmake \
            git \
            python3.10 \
            python3.10-dev \
            python3-pip \
            libomp-dev \
            libgmp-dev \
            libgtest-dev
          sudo apt clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Build Google Test
        run: |
          cd /usr/src/googletest && \
          sudo cmake CMakeLists.txt && \
          sudo make && \
          sudo cp lib/*.a /usr/lib

      - name: Install Python Packages
        run: |
          pip3 install --upgrade pip
          pip3 install \
            pandas==2.2.3 \
            pgmpy==0.1.26 \
            pulp==2.9.0 \
            pytest==8.3.3

      - name: Build the Project
        run: chmod +x build.sh && ./build.sh

      - name: Run Tests
        run: chmod +x test.sh && ./test.sh
